### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/1FF/laravel-mongodb-cache/pull/20/commits/ee11f54a78d4f64ee97b689ced4e43d7644eeeee?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-mongodb-cache.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "1ff/laravel-mongodb-cache": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Review by koprinski — APPROVED** [review]

**Comment by spont4e** [comment]
We waiting for [jenssegers/mongodb](https://github.com/jenssegers/laravel-mongodb/issues/2500) to support [Laravel 10](https://github.com/laravel/laravel)

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb[v3.9.0, ..., v3.9.5] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - 1ff/laravel-mongodb-cache dev-l10-compatibility requires jenssegers/mongodb ~3.9 -> satisfiable by jenssegers/mongodb[v3.9.0, ..., v3.9.5].
    - Root composer.json requires 1ff/laravel-mongodb-cache dev-l10-compatibility -> satisfiable by 1ff/laravel-mongodb-cache[dev-l10-compatibility].
```

**Comment by spont4e** [comment]
Declined

**Pull request closed without merging**
